### ISSUE TITLE
Jesus Danery Lazo López cuadro comparativo 

### ISSUE THREAD

**Issue by Dasus2332** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Dasus2332#3]
[Jesus Danery Lazo López cuadro comparativo .pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Dasus2332/files/9748022/Jesus.Danery.Lazo.Lopez.cuadro.comparativo.pdf)

**Comment by josealfredo79** [comment]
Calificacion 17

**Comment by josealfredo79** [comment]
Revisado...
